In [7]:
import torch
from model.layers.topology import TopologyModule

topo = TopologyModule()
a = torch.randn(2, 3, 4)
b = topo(a)
d = (b - a).mean()
aa = []
aa.append(d)
print(sum(aa) / len(aa))

tensor(0.3650)


In [16]:
import torch
import torch.nn as nn
from torch.nn import CrossEntropyLoss

ce = nn.CrossEntropyLoss()
so = nn.Softmax(dim=1)
a = torch.randn(2, 5, 3) # (B, C, N)
print(a)
aa = so(a)
b = torch.empty(2, 3, dtype=torch.long).random_(5) # (B, N)
print(aa)
print(b)
loga = torch.log(aa)
print(loga)
loss = ce(a, b)
print(loss)

ans = 0
for i in range(2):
    for j in range(3):
        ans = ans + loga[i,b[i,j],j]
print(ans / 6.)

tensor([[[ 0.4460, -0.2561,  0.8519],
         [-0.6642,  1.0791,  1.6099],
         [-0.7533, -0.8015, -0.8411],
         [-0.6531,  1.1243,  0.0605],
         [-0.6303,  1.2920,  0.0657]],

        [[ 0.9305, -0.5332, -0.6160],
         [ 0.2539, -0.3506,  1.2770],
         [-0.8902, -1.2303,  0.2275],
         [-0.2055, -0.5305, -0.0584],
         [ 0.2947, -1.6534,  2.1372]]])
tensor([[[0.4338, 0.0711, 0.2366],
         [0.1430, 0.2703, 0.5049],
         [0.1308, 0.0412, 0.0435],
         [0.1445, 0.2828, 0.1072],
         [0.1479, 0.3345, 0.1078]],

        [[0.3967, 0.2483, 0.0365],
         [0.2017, 0.2980, 0.2423],
         [0.0642, 0.1237, 0.0848],
         [0.1274, 0.2490, 0.0637],
         [0.2101, 0.0810, 0.5727]]])
tensor([[3, 3, 3],
        [0, 2, 1]])
tensor([[[-0.8351, -2.6433, -1.4414],
         [-1.9452, -1.3081, -0.6834],
         [-2.0343, -3.1887, -3.1345],
         [-1.9341, -1.2629, -2.2329],
         [-1.9113, -1.0952, -2.2277]],

        [[-0.9246, -1.3931, -3.